{
    'name': 'Odoo Reportbro',
    'version': '1.0',
    'summary': 'report designer',
    'author': 'huaqiangyan@163.com',
    'website': 'https://github.com/huakkai',
    'category': 'Tools',
    'license': 'GPL-3',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/report_report.xml',
        'views/report_template_js.xml',
    ],
    'qweb': [
        'static/src/xml/report_template.xml',
    ],
    'js': ["static/src/js/*.js"],
    'js': ["static/src/dist/*.js"],
    'js': ["static/src/dist/ext/*.js"],
    'css': ["static/src/dist/*.css"],
    'css': ["static/src/dist/ext/*.css"],
    'application': True,
    'installable': True,
}
